generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tienda
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tienda
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Usuario: { credentials: [Admin] }
        id: {credentials: [Admin]}
      list:
        display: [=id,=nombre,telefono,direccion,codpos,poblacion,Usuario]
      filter:
        display: [nombre,telefono,direccion,codpos,poblacion,usuario_id]
      form:    ~
      edit:    ~
      new:     ~
