<?php

/**
 * BaseFranja
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tienda_id
 * @property integer $semana
 * @property string $desde
 * @property string $hasta
 * @property Tienda $Tienda
 * 
 * @method integer getTiendaId()  Returns the current record's "tienda_id" value
 * @method integer getSemana()    Returns the current record's "semana" value
 * @method string  getDesde()     Returns the current record's "desde" value
 * @method string  getHasta()     Returns the current record's "hasta" value
 * @method Tienda  getTienda()    Returns the current record's "Tienda" value
 * @method Franja  setTiendaId()  Sets the current record's "tienda_id" value
 * @method Franja  setSemana()    Sets the current record's "semana" value
 * @method Franja  setDesde()     Sets the current record's "desde" value
 * @method Franja  setHasta()     Sets the current record's "hasta" value
 * @method Franja  setTienda()    Sets the current record's "Tienda" value
 * 
 * @package    proximidad
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFranja extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('franja');
        $this->hasColumn('tienda_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Tienda operativa dentro de la franja',
             ));
        $this->hasColumn('semana', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'día de la semana',
             ));
        $this->hasColumn('desde', 'string', 5, array(
             'type' => 'string',
             'comment' => 'hora desde',
             'length' => 5,
             ));
        $this->hasColumn('hasta', 'string', 5, array(
             'type' => 'string',
             'comment' => 'hora hasta',
             'length' => 5,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tienda', array(
             'local' => 'tienda_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}