<?php

/**
 * BaseTienda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $telefono
 * @property string $direccion
 * @property string $codpos
 * @property string $poblacion
 * @property double $latitud
 * @property double $longitud
 * @property integer $usuario_id
 * @property sfGuardUser $Usuario
 * @property Servicio $Servicio
 * @property Franja $Franja
 * 
 * @method string      getNombre()     Returns the current record's "nombre" value
 * @method string      getTelefono()   Returns the current record's "telefono" value
 * @method string      getDireccion()  Returns the current record's "direccion" value
 * @method string      getCodpos()     Returns the current record's "codpos" value
 * @method string      getPoblacion()  Returns the current record's "poblacion" value
 * @method double      getLatitud()    Returns the current record's "latitud" value
 * @method double      getLongitud()   Returns the current record's "longitud" value
 * @method integer     getUsuarioId()  Returns the current record's "usuario_id" value
 * @method sfGuardUser getUsuario()    Returns the current record's "Usuario" value
 * @method Servicio    getServicio()   Returns the current record's "Servicio" value
 * @method Franja      getFranja()     Returns the current record's "Franja" value
 * @method Tienda      setNombre()     Sets the current record's "nombre" value
 * @method Tienda      setTelefono()   Sets the current record's "telefono" value
 * @method Tienda      setDireccion()  Sets the current record's "direccion" value
 * @method Tienda      setCodpos()     Sets the current record's "codpos" value
 * @method Tienda      setPoblacion()  Sets the current record's "poblacion" value
 * @method Tienda      setLatitud()    Sets the current record's "latitud" value
 * @method Tienda      setLongitud()   Sets the current record's "longitud" value
 * @method Tienda      setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Tienda      setUsuario()    Sets the current record's "Usuario" value
 * @method Tienda      setServicio()   Sets the current record's "Servicio" value
 * @method Tienda      setFranja()     Sets the current record's "Franja" value
 * 
 * @package    proximidad
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTienda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tienda');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'comment' => 'Nombre de la tienda',
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Teléfono de la tienda',
             'length' => 10,
             ));
        $this->hasColumn('direccion', 'string', 80, array(
             'type' => 'string',
             'comment' => 'Dirección de la tienda',
             'length' => 80,
             ));
        $this->hasColumn('codpos', 'string', 5, array(
             'type' => 'string',
             'comment' => 'Dirección de la tienda',
             'length' => 5,
             ));
        $this->hasColumn('poblacion', 'string', 20, array(
             'type' => 'string',
             'comment' => 'Población de la tienda',
             'length' => 20,
             ));
        $this->hasColumn('latitud', 'double', 15, array(
             'type' => 'double',
             'scale' => 10,
             'comment' => 'latitud de la tienda',
             'length' => 15,
             ));
        $this->hasColumn('longitud', 'double', 15, array(
             'type' => 'double',
             'scale' => 10,
             'comment' => 'longitud de la tienda',
             'length' => 15,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Usuario responsable de la tienda',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Servicio', array(
             'local' => 'id',
             'foreign' => 'tienda_id'));

        $this->hasOne('Franja', array(
             'local' => 'id',
             'foreign' => 'tienda_id'));
    }
}