<?php

/**
 * BaseFranjaTienda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $franja_id
 * @property integer $tienda_id
 * @property Franja $Franja
 * @property Tienda $Tienda
 * 
 * @method integer      getFranjaId()  Returns the current record's "franja_id" value
 * @method integer      getTiendaId()  Returns the current record's "tienda_id" value
 * @method Franja       getFranja()    Returns the current record's "Franja" value
 * @method Tienda       getTienda()    Returns the current record's "Tienda" value
 * @method FranjaTienda setFranjaId()  Sets the current record's "franja_id" value
 * @method FranjaTienda setTiendaId()  Sets the current record's "tienda_id" value
 * @method FranjaTienda setFranja()    Sets the current record's "Franja" value
 * @method FranjaTienda setTienda()    Sets the current record's "Tienda" value
 * 
 * @package    proximidad
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFranjaTienda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('franja_tienda');
        $this->hasColumn('franja_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tienda_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Franja', array(
             'local' => 'franja_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Tienda', array(
             'local' => 'tienda_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}