<?php

/**
 * BaseFranja
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dia_semana
 * @property string $franja_desde
 * @property string $franja_hasta
 * @property Doctrine_Collection $FranjaTienda
 * 
 * @method integer             getDiaSemana()    Returns the current record's "dia_semana" value
 * @method string              getFranjaDesde()  Returns the current record's "franja_desde" value
 * @method string              getFranjaHasta()  Returns the current record's "franja_hasta" value
 * @method Doctrine_Collection getFranjaTienda() Returns the current record's "FranjaTienda" collection
 * @method Franja              setDiaSemana()    Sets the current record's "dia_semana" value
 * @method Franja              setFranjaDesde()  Sets the current record's "franja_desde" value
 * @method Franja              setFranjaHasta()  Sets the current record's "franja_hasta" value
 * @method Franja              setFranjaTienda() Sets the current record's "FranjaTienda" collection
 * 
 * @package    stetik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFranja extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('franja');
        $this->hasColumn('dia_semana', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'día de la semana',
             ));
        $this->hasColumn('franja_desde', 'string', 5, array(
             'type' => 'string',
             'comment' => 'franja desde',
             'length' => 5,
             ));
        $this->hasColumn('franja_hasta', 'string', 5, array(
             'type' => 'string',
             'comment' => 'franja hasta',
             'length' => 5,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FranjaTienda', array(
             'local' => 'id',
             'foreign' => 'franja_id'));
    }
}