<?php

/**
 * BaseServicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property text $descripcion
 * @property integer $tienda_id
 * @property string $imagen
 * @property Tienda $Tienda
 * 
 * @method string   getTitulo()      Returns the current record's "titulo" value
 * @method text     getDescripcion() Returns the current record's "descripcion" value
 * @method integer  getTiendaId()    Returns the current record's "tienda_id" value
 * @method string   getImagen()      Returns the current record's "imagen" value
 * @method Tienda   getTienda()      Returns the current record's "Tienda" value
 * @method Servicio setTitulo()      Sets the current record's "titulo" value
 * @method Servicio setDescripcion() Sets the current record's "descripcion" value
 * @method Servicio setTiendaId()    Sets the current record's "tienda_id" value
 * @method Servicio setImagen()      Sets the current record's "imagen" value
 * @method Servicio setTienda()      Sets the current record's "Tienda" value
 * 
 * @package    stetik
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio');
        $this->hasColumn('titulo', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'comment' => 'Nombre del servicio',
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'comment' => 'Descripción del servicio',
             ));
        $this->hasColumn('tienda_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Tienda que ofrece el servicio',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Imagen del servicio',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tienda', array(
             'local' => 'tienda_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}