<?php

/**
 * FranjaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FranjaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FranjaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Franja');
    }
}