<?php

/**
 * FranjaTiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FranjaTiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FranjaTiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FranjaTienda');
    }
}