<?php

/**
 * TiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tienda');
    }
}