generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Servicio
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          servicio
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: {credentials: [Admin]}
      list:
        display:
          [id,=titulo,descripcion,tienda,_imagen,precio]
      filter:
        display:
          [titulo,descripcion,tienda_id,slug]
      form:    ~
      edit:    ~
      new:     ~
